### ISSUE TITLE
request: musl 1.2.4 support for Alpine 3.18 users

### ISSUE THREAD

**Issue by dalbitresb12** [sapphiredev/type#464]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues and pull requests

### Feature description

The prebuilt binaries do not include musl 1.2.4, which is used by Alpine 3.18. I believe this was just recently released (start of June if I'm correct) so that's why there is no prebuilt for musl (last release of this package was on April).

I checked #429 and the solution seems to be to use Yarn, but it didn't mention that it required Python to be installed in the Docker image. I had to add the following line to my Dockerfile as suggested [here](https://stackoverflow.com/a/73709343/15040387):

```dockerfile
RUN apk add --no-cache libc6-compat python3 build-base gcc
```

### Desired solution

Prebuilt binaries for musl 1.2.4 in releases would prevent users from having to install Python into the Docker build image.

_I know I can use multi-stage builds to remove Python from the final image -- I'm using that for my image. But having the prebuilt for musl could reduce build times._

### Alternatives considered

Building manually works with Yarn and Python installed in the Docker build image.

### Additional context

Here's the log generated from the failed build by node-pre-gyp when I didn't have Python installed, just in case it is needed:

<details>
<summary>build.log</summary>

```
# This file contains the result of Yarn building a package (@sapphire/type@npm:2.4.0)
# Script name: install

node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.4.5
node-pre-gyp info using node@18.16.1 | linux | x64
node-pre-gyp info check checked for "/app/node_modules/@sapphire/type/prebuild/type-node-v108-linux-x64-musl-1.2.4/type.node" (not found)
node-pre-gyp http GET https://github.com/sapphiredev/type/releases/download/v2.4.0/type-v2.4.0-node-v108-linux-x64-musl-1.2.4.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/sapphiredev/type/releases/download/v2.4.0/type-v2.4.0-node-v108-linux-x64-musl-1.2.4.tar.gz
node-pre-gyp WARN Pre-built binaries not installable for @sapphire/type@2.4.0 and node@18.16.1 (node-v108 ABI, musl) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/sapphiredev/type/releases/download/v2.4.0/type-v2.4.0-node-v108-linux-x64-musl-1.2.4.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.0
gyp info using node@18.16.1 | linux | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.0
gyp info using node@18.16.1 | linux | x64
gyp ERR! find Python
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (/app/node_modules/node-gyp/lib/find-python.js:330:47)
gyp ERR! stack     at PythonFinder.runChecks (/app/node_modules/node-gyp/lib/find-python.js:159:21)
gyp ERR! stack     at PythonFinder.<anonymous> (/app/node_modules/node-gyp/lib/find-python.js:202:16)
gyp ERR! stack     at PythonFinder.execFileCallback (/app/node_modules/node-gyp/lib/find-python.js:294:16)
gyp ERR! stack     at exithandler (node:child_process:427:5)
gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:439:5)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:289:12)
gyp ERR! stack     at onErrorNT (node:internal/child_process:476:16)
gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
gyp ERR! System Linux 5.15.90.1-microsoft-standard-WSL2
gyp ERR! command "/usr/local/bin/node" "/app/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/app/node_modules/@sapphire/type/prebuild/type-node-v108-linux-x64-musl-1.2.4/type.node" "--module_name=type" "--module_path=/app/node_modules/@sapphire/type/prebuild/type-node-v108-linux-x64-musl-1.2.4" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v108"
gyp ERR! cwd /app/node_modules/@sapphire/type
gyp ERR! node -v v18.16.1
gyp ERR! node-gyp -v v9.3.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /app/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/app/node_modules/@sapphire/type/prebuild/type-node-v108-linux-x64-musl-1.2.4/type.node --module_name=type --module_path=/app/node_modules/@sapphire/type/prebuild/type-node-v108-linux-x64-musl-1.2.4 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/app/node_modules/@discordjs/node-pre-gyp/lib/util/compile.js:85:20)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
node-pre-gyp ERR! System Linux 5.15.90.1-microsoft-standard-WSL2
node-pre-gyp ERR! command "/usr/local/bin/node" "/app/node_modules/@discordjs/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /app/node_modules/@sapphire/type
node-pre-gyp ERR! node -v v18.16.1
node-pre-gyp ERR! node-pre-gyp -v v0.4.5
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /app/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/app/node_modules/@sapphire/type/prebuild/type-node-v108-linux-x64-musl-1.2.4/type.node --module_name=type --module_path=/app/node_modules/@sapphire/type/prebuild/type-node-v108-linux-x64-musl-1.2.4 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
```

</details>

**Comment by favna** [comment]
I will give you the exact same response as I gave #429. We are not at the liberty of choosing which prebuilt binaries we ship. It's all up to what GitHub actions offers at the time of running a release and we simply cannot provide versions of every single musl/glibc/cmake/etc. 

You should always have the dependencies ready to build any native libraries yourself, that's just a fact when working with native libraries.

**Comment by dalbitresb12** [comment]
Sure, I totally missed that comment. Sorry about that! It's understandable. Thanks for making this awesome framework!

**Comment by favna** [comment]
`type-v2.4.0-node-v115-linux-x64-musl-1.2.4.tar.gz` was added. I [made a CI script](https://github.com/sapphiredev/type/blob/main/.github/workflows/manual-asset-updater.yml) that can be triggered through a workflow dispatch to update an existing release.

Granted this is very much an on-request thing because I too did notice that some Docker image I was working on didn't get a prebuilt not too long ago which was probably the same musl. I'm not going to monitor musl releases to then kick off runs here, especially considering when a musl has been released it's still up to GitHub to update their runner environments.
